FROM node:20-slim

WORKDIR /app

# Enable pnpm via corepack
RUN corepack enable

# Install dependencies first (enables perfect layer caching)
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# Copy the rest of your source code
COPY . .


RUN npx prisma generate
COPY docker-entrypoint.sh ./
RUN chmod +x docker-entrypoint.sh

# Expose Node backend port
EXPOSE 8000

ENTRYPOINT ["sh", "./docker-entrypoint.sh"]
