import express from "express";
import { verify_access_token } from "../authentication/authentication.middleware.js";
import ProfileController from "./profile.controller.js";
import ProfileService from "./profile.service.js";
import ProfileRepository from "./profile.repository.js";
import IntegrationController from "../integration/integration.controller.js";
import IntegrationService from "../integration/integration.service.js";
import GoogleOAuthService from "../integration/google-oauth.service.js";
import IntegrationRepository from "../integration/integration.repository.js";
const router = express.Router();
router.use(verify_access_token);
const profileRepository = new ProfileRepository();
const profileService = new ProfileService(profileRepository);
const profileController = new ProfileController(profileService);
const googleAuthService = new GoogleOAuthService();
const integrationRepository = new IntegrationRepository();
const integrationService = new IntegrationService(googleAuthService, integrationRepository);
const integrationController = new IntegrationController(integrationService);
router.post("/", profileController.create_profile);
router.post("/:profile_id/integration/google/connect", integrationController.google_connect);
router.get("/:profile_id/integration/google/get_gmail_integration", integrationController.get_gmail_integration);
router.get("/:profile_id/integration/google/refresh_token", integrationController.refresh_google_token);
export { router };
//# sourceMappingURL=profile.route.js.map